# Generated by Django 5.0.7 on 2024-09-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Text of the blog cart'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Text of the blog cart'),
        ),
    ]
