# Generated by Django 5.0.7 on 2024-08-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is this the main version of product?'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantity in number', null=True, verbose_name='Quantity of the product'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='product.product'),
        ),
    ]
