# Generated by Django 5.0.7 on 2024-09-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productversion_is_main_productversion_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='product.manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='product.manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
