# Generated by Django 5.0.7 on 2024-09-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_az_product_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_en',
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
