# Generated by Django 5.0.7 on 2024-09-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
    ]
