# Generated by Django 5.0.7 on 2024-09-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_email_az_customuser_email_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_az',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name_az',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name_az',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name_en',
        ),
    ]
